# OneStrokeRune.gd  (mushrooms)
# Draw ONE continuous line that touches every node exactly once, moving only between orthogonally
# adjacent nodes. The puzzle is generated by first finding a real Hamiltonian path, so a solution
# always exists. Click the glowing start node, then click adjacent nodes to extend; click the
# previous node to back up. RESET restarts, LEAVE cancels. Contract: start(label, difficulty) +
# finished(success).
class_name OneStrokeRune
extends Control

signal finished(success: bool)

var _cols := 3
var _rows := 3
var _nodes: Array[Vector2] = []   # screen positions; index = r*_cols + c
var _path: Array[int] = []        # visited node indices, in order
var _start := 0
var _done := false
var _ok := false
var _label := ""
var _reset_rect := Rect2()
var _leave_rect := Rect2()

func start(label: String, difficulty: float = 0.5) -> void:
	_label = label
	_cols = 3 + (1 if difficulty >= 0.5 else 0)      # 3x3 .. up to 4x4 with difficulty
	_rows = 3 + (1 if difficulty >= 0.8 else 0)
	_layout()
	var order := _hamiltonian()
	_start = order[0] if order.size() > 0 else 0
	_path = [_start]
	_done = false
	_ok = false
	set_anchors_preset(PRESET_FULL_RECT)
	size = get_viewport_rect().size
	mouse_filter = Control.MOUSE_FILTER_STOP
	visible = true
	queue_redraw()

func _layout() -> void:
	var vp := get_viewport_rect().size
	var gap := 76.0
	var ox := vp.x * 0.5 - (_cols - 1) * gap * 0.5
	var oy := vp.y * 0.5 - (_rows - 1) * gap * 0.5 + 12.0
	_nodes = []
	for r in _rows:
		for c in _cols:
			_nodes.append(Vector2(ox + c * gap, oy + r * gap))

func _neighbors(idx: int) -> Array:
	var c := idx % _cols
	var r := int(idx / _cols)
	var out: Array = []
	if c > 0: out.append(idx - 1)
	if c < _cols - 1: out.append(idx + 1)
	if r > 0: out.append(idx - _cols)
	if r < _rows - 1: out.append(idx + _cols)
	return out

func _is_adjacent(a: int, b: int) -> bool:
	return _neighbors(a).has(b)

func _hamiltonian() -> Array:
	var total := _cols * _rows
	for _attempt in range(80):
		var s := randi() % total
		var visited := {s: true}
		var path: Array = [s]
		if _dfs(s, visited, path, total):
			return path
	return [0]

func _dfs(node: int, visited: Dictionary, path: Array, total: int) -> bool:
	if path.size() == total:
		return true
	var nbrs := _neighbors(node)
	nbrs.shuffle()
	for nb in nbrs:
		if not visited.has(nb):
			visited[nb] = true
			path.append(nb)
			if _dfs(nb, visited, path, total):
				return true
			path.pop_back()
			visited.erase(nb)
	return false

func _node_at(m: Vector2) -> int:
	for i in range(_nodes.size()):
		if m.distance_to(_nodes[i]) <= 20.0:
			return i
	return -1

func _input(event: InputEvent) -> void:
	if _done:
		return
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		get_viewport().set_input_as_handled()
		var m := get_global_mouse_position()
		if _leave_rect.has_point(m):
			_finish(false)
			return
		if _reset_rect.has_point(m):
			_path = [_start]
			queue_redraw()
			return
		var hit := _node_at(m)
		if hit == -1:
			return
		var cur: int = _path[_path.size() - 1]
		if _path.size() >= 2 and hit == _path[_path.size() - 2]:
			_path.pop_back()                                  # step back
		elif not _path.has(hit) and _is_adjacent(hit, cur):
			_path.append(hit)
			if _path.size() == _nodes.size():
				_finish(true)
		queue_redraw()

func _finish(ok: bool) -> void:
	_done = true
	_ok = ok
	queue_redraw()
	await get_tree().create_timer(0.6).timeout
	visible = false
	finished.emit(_ok)

func _draw() -> void:
	var vp := get_viewport_rect().size
	draw_rect(Rect2(Vector2.ZERO, vp), Color(0, 0, 0, 0.58))
	var font := ThemeDB.fallback_font
	draw_string(font, Vector2(0, _nodes[0].y - 90), _label, HORIZONTAL_ALIGNMENT_CENTER, vp.x, 20, ViewConfig.COL_TEXT)
	draw_string(font, Vector2(0, _nodes[0].y - 66), "One stroke: touch every node once, only between neighbours",
		HORIZONTAL_ALIGNMENT_CENTER, vp.x, 14, ViewConfig.COL_TEXT_OFF)
	# traced line
	for i in range(_path.size() - 1):
		draw_line(_nodes[_path[i]], _nodes[_path[i + 1]], Color(0.35, 0.80, 0.42), 6.0)
	# nodes
	for i in range(_nodes.size()):
		var col := Color(0.45, 0.47, 0.55)
		if i == _start:
			col = Color(0.95, 0.80, 0.35)
		elif _path.has(i):
			col = Color(0.55, 0.90, 0.62)
		draw_circle(_nodes[i], 9.0, col)
	# current head ring
	if _path.size() > 0:
		draw_arc(_nodes[_path[_path.size() - 1]], 14.0, 0, TAU, 24, Color(1, 1, 1), 2.0)
	# buttons + result
	var by := _nodes[_nodes.size() - 1].y + 60.0
	_reset_rect = _button(font, vp.x * 0.5 - 130, by, "RESET")
	_leave_rect = _button(font, vp.x * 0.5 + 12, by, "LEAVE")
	if _done:
		var txt := "Aligned!" if _ok else "Left"
		draw_string(font, Vector2(0, by + 52), txt, HORIZONTAL_ALIGNMENT_CENTER, vp.x,
			22, ViewConfig.COL_GOLD if _ok else ViewConfig.COL_TEXT_OFF)

func _button(font: Font, x: float, y: float, label: String) -> Rect2:
	var r := Rect2(x, y, 118, 34)
	draw_rect(r, Color(0.20, 0.21, 0.27))
	draw_rect(r, ViewConfig.COL_FRAME, false, 2.0)
	draw_string(font, Vector2(r.position.x, r.position.y + 23), label, HORIZONTAL_ALIGNMENT_CENTER, r.size.x, 15, ViewConfig.COL_TEXT)
	return r
